apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendServiceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontendServiceName }}
spec:
  type: {{ .Values.frontendService.type }}
  ports:
    - port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendContainerPort }}
  selector:
    app: {{ .Values.frontendContainerName }}
