apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendServiceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backendServiceName }}
spec:
  type: {{ .Values.backendService.type }}
  ports:
    - nodePort: {{ .Values.backendService.nodePort }}
      port: {{ .Values.backendContainerPort }}
      targetPort: {{ .Values.backendContainerPort }}
  selector:
    app: {{ .Values.backendTemplateAppName }}
