apiVersion: v1
kind: Service
metadata:
  {{- with .Values.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.frontendServiceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontendServiceName }}
spec:
  loadBalancerIP: {{ .Values.azureLoadBalancerIP }}
  type: {{ .Values.frontendService.type }}
  ports:
    - port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendContainerPort }}
  selector:
    app: {{ .Values.frontendContainerName }}
