apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisServiceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.redisServiceName }}
spec:
  type: {{ .Values.redisService.type }}
  ports:
    - port: {{ .Values.redisService.port }}
      targetPort: {{ .Values.redisContainerPort }}
  selector:
    app: {{ .Values.redisDeploymentName  }}
