#███╗   ██╗ █████╗ ███╗   ███╗███████╗███████╗██████╗  █████╗  ██████╗███████╗
#████╗  ██║██╔══██╗████╗ ████║██╔════╝██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝
#██╔██╗ ██║███████║██╔████╔██║█████╗  ███████╗██████╔╝███████║██║     █████╗
#██║╚██╗██║██╔══██║██║╚██╔╝██║██╔══╝  ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝
#██║ ╚████║██║  ██║██║ ╚═╝ ██║███████╗███████║██║     ██║  ██║╚██████╗███████╗
#╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝
apiVersion: v1
kind: Namespace
metadata:
  name: realtimepixel-prod
  labels:
    name: realtimepixel-prod
---
#██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗███╗   ███╗███████╗███╗   ██╗████████╗
#██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝████╗ ████║██╔════╝████╗  ██║╚══██╔══╝
#██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝ ██╔████╔██║█████╗  ██╔██╗ ██║   ██║
#██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝  ██║╚██╔╝██║██╔══╝  ██║╚██╗██║   ██║
#██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║   ██║ ╚═╝ ██║███████╗██║ ╚████║   ██║
#╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝
# Scale horizontally Redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: realtimepixel-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: realtimepixel-redis
          image: realtimepixel_redis:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6379

---
# Scale horizontally the web api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: realtimepixel-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: realtimepixel-backend
          image: realtimepixel_backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3500
          env:
            - name: SERVER_IP
              value: "webapi" # Service selector app
            - name: SERVER_PORT
              value: "80"
            - name: REDIS_IP
              value: "redis" # Service selector app
            - name: REDIS_PORT
              value: "6379"
            - name: CLIENT_IP
              value: "webapplication" # Service selector app
            - name: DOCKER_CLIENT_PORT_FORWARD
              value: "3501"
---
# Scale horizontally the web application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: realtimepixel-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapplication
  template:
    metadata:
      labels:
        app: webapplication
    spec:
      containers:
        - name: realtimepixel-frontend
          image: realtimepixel_frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3501
---
#███████╗███████╗██████╗ ██╗   ██╗██╗ ██████╗███████╗
#██╔════╝██╔════╝██╔══██╗██║   ██║██║██╔════╝██╔════╝
#███████╗█████╗  ██████╔╝██║   ██║██║██║     █████╗
#╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██║██║     ██╔══╝
#███████║███████╗██║  ██║ ╚████╔╝ ██║╚██████╗███████╗
#╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚═╝ ╚═════╝╚══════╝

# Load-Balancer for the web application
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: realtimepixel-prod
  labels:
    app: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: webapplication
  ports:
    - nodePort: 30062
      port: 3501
      targetPort: 3501
---
# Load-Balancer for the web api
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: realtimepixel-prod
  labels:
    app: backendend-service
spec:
  type: NodePort
  selector:
    app: webapi
  ports:
    - nodePort: 30063
      port: 3500
      targetPort: 3500
---
# Load-Balancer for the Redis
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: realtimepixel-prod
  labels:
    app: redis-service
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - nodePort: 30064
      port: 6379
      targetPort: 6379
---

