import os

# Read the environment variables from the .env file
__location__ = os.path.realpath(os.path.join(
    os.getcwd(), os.path.dirname(__file__)))
f = open(os.path.join(__location__, '.env'))
lines = f.read().splitlines()

# Extract all the key-value of each line
keyValues = []
for line in lines:
    if line.find("=") >= 0 and line.strip().find("#") != 0:
        lineSplit = line.split("=")
        left = lineSplit[0].strip()
        right = lineSplit[1].strip()
        if right.find("#") > 0:
            right = right[:right.find("#")-1]
        keyValues.append([left, right])

# Create the TS file
tsFile = "/**\n ** This file is generated by scripts/envToConsts.py\n **/\n"
tsFile += "export const ENV_VARIABLES = {\n"

for pair in keyValues:
    if unicode(pair[1], "utf-8").isnumeric():
        tsFile += "  " + pair[0] + ": " + pair[1] + ",\n"
    elif pair[1] == "true" or pair[1] == "false" or pair[1] == "TRUE" or pair[1] == "FALSE":
        tsFile += "  " + pair[0] + ": " + pair[1].lower() + ",\n"
    else:
        tsFile += "  " + pair[0] + ": \"" + pair[1].lower() + "\",\n"
tsFile += "}"

# Write the file on disk
f = open(os.path.join(__location__,
         '../node/src/generated/constants_env.ts'), "w")
f.write(tsFile)
f.close()
