name: Docker Image CI
on:
  workflow_dispatch:

  push:
    branches: ["master"]

# Environment variables available to all jobs and steps in this workflow
env:
  ENVIRONMENT: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Docker Auhentication"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Build and Push Redis Image"  
        run: |
          docker build -f services/redis/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/realtimepixel_redis:${{ github.sha }} --target ${{env.ENVIRONMENT}} --build-arg NODE_ENV=${{env.ENVIRONMENT}} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/realtimepixel_redis:${{ github.sha }}

      - name: "Build and Push Backend Image"
        run: |
          docker build -f services/backend/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/realtimepixel_backend:${{ github.sha }} --target ${{env.ENVIRONMENT}} --build-arg NODE_ENV=${{env.ENVIRONMENT}} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/realtimepixel_backend:${{ github.sha }}

      - name: "Build and Push Frontend Image"
        run: |
          docker build -f services/frontend/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/realtimepixel_frontend:${{ github.sha }} --target ${{env.ENVIRONMENT}} --build-arg NODE_ENV=${{env.ENVIRONMENT}} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/realtimepixel_frontend:${{ github.sha }}

      # - name: "Deploy to Azure Container Instances: Backend"
      #   uses: "azure/aci-deploy@v1"
      #   with:
      #     resource-group: ${{ secrets.RESOURCE_GROUP }}
      #     dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
      #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
      #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #     registry-username: ${{ secrets.AZURE_CLIENT_ID }}
      #     registry-password: ${{ secrets.AZURE_SECRET_ID }}
      #     name: realtimepixel
      #     location: "west us"
